num1 = input('').strip()
num2 = input('').strip()

soma = float(num1) + float(num2)
somaS = str(float(num1)) + str(int(num2))
mult = float(num1) * float(num2)
multS = str(float(num1)) * int(num2)
div = float(num1) / float(num2)
divInt = float(num1) // float(num2)
exp = float(num1) ** float(num2)
rest = float(num1) % float(num2)

print(f'{soma}')
print(f'{somaS}')
print(f'{mult}')
print(f'{multS}')
print(f'{div}')
print(f'{divInt}')
print(f'{exp}')
print(f'{rest}')