num1 = input('Digite o primeiro número: ')
num2 = input('Digite o segundo número: ')

soma = float(num1) + float(num2)
somaS = str(float(num1)) + str(int(num2))
mult = float(num1) * float(num2)
multS = str(float(num1)) * int(num2)
div = float(num1) / float(num2)
divInt = float(int(num1) // int(num2))
exp = float(num1) ** float(num2)
rest = float(num1) % float(num2)
# print(f'{}')
print(f'A soma é igual a: {soma}')
print(f'A soma das strings é igual a: {somaS}')
print(f'A mutiplicação é igual a: {mult}')
print(f'A mutiplicação das strings é igual a: {multS}')
print(f'A divisão é igual a: {div}')
print(f'A divisão inteira é igual a: {divInt}')
print(f'A exponenciação é igual a: {exp}')
print(f'O resto da divisão é igual a: {rest}')